name: Build and Push Flink Image to Harbor

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push_to_harbor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }} 
          username: ${{ secrets.HARBOR_USERNAME }} 
          password: ${{ secrets.HARBOR_PASSWORD }} 

      - name: Build and push Docker image to Harbor
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/flink-apps/flink-with-s3:1.20.1
